# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='date started')),
                ('end_date', models.DateTimeField(verbose_name='date finished')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=500)),
                ('salt', models.CharField(max_length=500)),
                ('hours_per_day', models.IntegerField()),
                ('balance_correction', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='date started')),
                ('end_time', models.DateTimeField(verbose_name='date finished')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.User')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.User'),
        ),
    ]
