# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='Work',
        ),
    ]
