# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20160519_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hours_per_day',
            new_name='minutes_per_day',
        ),
    ]
