# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_auto_20160519_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance_correction',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
